### PR TITLE
JER Smearing update

### PR DESCRIPTION
**Pull request by jdandoy**
Implement JER Smearing for 2.3.17.  The JER Tool has been implemented in the JetCalibrator and smears jets after calibration and JES Uncertainties, but before JVT recalculation and cleaning (both pT dependent).  Three new options are added to the config file:

JERUncertConfig         JetResolution/Prerec2015_xCalib_2012JER_ReducedTo9NP_Plots.root
JERFullSys        false
JERApplyNominal   false

JERFullSys can be set to false for us now, giving only one NP for smearing MC.  Setting it to true gives many NPs that smear MC and data.

JERApplyNominal is experimental and should not be used by us now, but it is implemented.  This will also smear every JES systematic uncertainty TTree.

If this is accepted I will create a new tag for xAODAnaHelpers and for DijetResonanceAlgo for use with 2.3.18.

@gfacini  @johnda102 @kratsg

### CODE REVIEW

**Comment by kratsg** [comment]
What version is this running on? 2.3.17 or 2.3.18? We're currently on 2.3.16 I think? @mmilesi

**Comment by jdandoy** [comment]
It's run on 2.3.17, but I don't anticipate any issues with the move to
2.3.18 which is high priority for EPS.

Jeff

**Comment by kratsg** [comment]
@jdandoy Let me update the travis file so it has the right version. If we change versions, we need to update the testing utility and the readme so everyone knows what version we're on.

**Comment by kratsg** [comment]
@jdandoy This fails on 2.3.18

```
/home/jenkins/workspace/xAH/main/xAODAnaHelpers/Root/MuonEfficiencyCorrector.cxx: In member function ‘virtual EL::StatusCode MuonEfficiencyCorrector::executeSF(const MuonContainer*, const EventInfo*, unsigned int)’:
/home/jenkins/workspace/xAH/main/xAODAnaHelpers/Root/MuonEfficiencyCorrector.cxx:561:76: error: no matching function for call to ‘CP::MuonTriggerScaleFactors::getTriggerScaleFactor(const MuonContainer&, double&)’
       if ( m_muonTrigSFTool->getTriggerScaleFactor( *inputMuons, triggerSF ) != CP::CorrectionCode::Ok ) {
                                                                            ^
/home/jenkins/workspace/xAH/main/xAODAnaHelpers/Root/MuonEfficiencyCorrector.cxx:561:76: note: candidate is:
In file included from /home/jenkins/workspace/xAH/main/xAODAnaHelpers/xAODAnaHelpers/MuonEfficiencyCorrector.h:13:0,
                 from /home/jenkins/workspace/xAH/main/xAODAnaHelpers/Root/MuonEfficiencyCorrector.cxx:31:
/home/jenkins/workspace/xAH/main/RootCoreBin/include/MuonEfficiencyCorrections/MuonTriggerScaleFactors.h:78:25: note: virtual CP::CorrectionCode CP::MuonTriggerScaleFactors::getTriggerScaleFactor(const MuonContainer&, Double_t&, std::string)
  virtual CorrectionCode getTriggerScaleFactor(const xAOD::MuonContainer& mucont,
                         ^
/home/jenkins/workspace/xAH/main/RootCoreBin/include/MuonEfficiencyCorrections/MuonTriggerScaleFactors.h:78:25: note:   candidate expects 3 arguments, 2 provided
make: *** [/home/jenkins/workspace/xAH/main/RootCoreBin/obj/x86_64-slc6-gcc48-opt/xAODAnaHelpers/obj/MuonEfficiencyCorrector.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by kratsg** [comment]
@jdandoy This works perfectly on 2.3.17 as is. There are errors with 2.3.18 -- if you're ok with that.

**Comment by mmilesi** [comment]
Let me guess....they changed again interfaces of some muon trigger tool from 17 to 18. This is so frustrating. Plus, what was the point of having 3 different versions released in the time of a week??

@jdandoy : can you stay on 2.3.17 for another few days?

**Comment by mmilesi** [comment]
@jdandoy 

You'll be happy to see this :smiley:

**Comment by kratsg** [comment]
Just to update - @mmilesi got this working on 2.3.18 since there is a bug with the Muon Interface being changed again. The current version of AB should be 2.3.18 now.

**Comment by mmilesi** [comment]
I am going to update the README

**Comment by jdandoy** [comment]
Sweet thanks a ton Marco!
