### ISSUE TITLE
xAH not compiling in Base,2.4.21

### ISSUE THREAD

**Issue by jmrolsson** [UCATLAS/xAODAnaHelpers#750]
xAH does not compile in Base,2.4.21 (but compiles just fine in 2.4.20)

- I tried the following:
git clone https://github.com/UCATLAS/xAODAnaHelpers.git
lsetup 'rcsetup Base,2.4.21'
rc find_packages
rc compile 

- Error (in METConstructor.cxx):
/share/home/jolsson/workarea/WorkAreaML/xAODAnaHelpers/Root/METConstructor.cxx:414:146: error: no matching function for call to ‘met::METMaker::rebuildMET(const char [7], xAOD::Type::ObjectType, xAOD::MissingETContainer*&, const DataVector<xAOD::Electron_v1>*, const MissingETAssociationMap*&)’
      RETURN_CHECK("METConstructor::execute()", m_metmaker->rebuildMET("RefEle", xAOD::Type::Electron, newMet, metElectrons.asDataVector(),

- Details:
https://gist.github.com/jmrolsson/4f6b72bf1c38ac9641b97333cfd17abb

**Comment by jdandoy** [comment]
We need to implement the changes listed [here](https://twiki.cern.ch/twiki/bin/view/AtlasProtected/EtmissRecommendationsRel20p7#Configuration_File), including the use of IMETMaker.  I think the input containers are already handled properly as they're stored in TSTore.
