### ISSUE TITLE
xAH does not compile in Base 2.4.9

### ISSUE THREAD

**Issue by ballen4** [UCATLAS/xAODAnaHelpers#599]
Current tag xAODAnaHelpers-00-03-34 does not compile in AnalysisBase 2.4.9 due to some changes to electron identification.

[See one of the offending changes here](https://svnweb.cern.ch/cern/wsvn/atlasoff?manualorder=1&op=comp&compare%5B0%5D=%2FPhysicsAnalysis%2FElectronPhotonID%2FElectronPhotonSelectorTools%2Ftrunk%2F&compare_rev%5B0%5D=734692&compare%5B1%5D=%2FPhysicsAnalysis%2FElectronPhotonID%2FElectronPhotonSelectorTools%2Ftrunk%2F&compare_rev%5B1%5D=734693&comparesubmit=Compare+Paths)

Some of the compilation errors can be fixed by including ElectronPhotonSelectorTools/LikelihoodEnums.h, but I have not determined where, if anywhere, the definitions for egammaPID::PID have wandered off to.

The errors seen on compile:

xAODAnaHelpers/xAODAnaHelpers/ParticlePIDManager.h:208:35: error: âPIDâ is not a member of âegammaPIDâ
         HelperClasses::EnumParser<egammaPID::PID> selectedWP_parser;

xAODAnaHelpers/xAODAnaHelpers/ParticlePIDManager.h:64:35: error: âMenuâ is not a member of âLikeEnumâ
         HelperClasses::EnumParser<LikeEnum::Menu> selectedWP_parser;

-Ben

**Comment by kratsg** [comment]
Hi @ballen4 -- as seen here (https://xaodanahelpers.readthedocs.io/en/latest/) -- the current tag is 2.4.9 for good reason. You're welcome to provide a pull request to update the code to work in 2.4.9.

However, this is super annoying that one of the header files in the release moved locations. I'll ask pathelp why this happened.

**Comment by kratsg** [comment]
Looks like they're gradual changes upstream in Athena? https://groups.cern.ch/group/hn-atlas-PATHelp/Lists/Archive/Flat.aspx?RootFolder=%2Fgroup%2Fhn-atlas-PATHelp%2FLists%2FArchive%2FAB%20release%202%2E4%2E8%20-%202%2E4%2E9%20header%20changes&FolderCTID=0x0120020084D7E80CB0C3394A8D54EF07C309B044

We'll need to fix this up now, unfortunately.

**Comment by kkrizka** [comment]
I just updated to 2.4.10 to get the latest calibrations, so I would be interested in getting this fixed. To summarize, the compilation fails due to two missing enums: `egammaPID::LikeEnum::Menu` and `egammaPID::PID`. Fixing the first one is easy, since it just needs a new include.

The second one confuses me. We only use the `IsEMTight`/`IsEMMedium`/`IsEMLoose` to quickly order the cut-based PID working points. Is it used for anything else? Christos' reply to @kratsg seems to indicate that it is not, which to me indicates that it is gone forever. I fixed it in my local version by replacing `egamma::PID` with a new enum in xAODAnaHelpers containing only these three points.

@mmilesi, you are the original author of the electron PID implementation in xAH. Can you comment if this makes sense?

**Comment by johnda102** [comment]
Hi All, 

  Just committed a fix that should deal with this.  It adds the new include needed and removes the deprecated egammaPID:PID enums.

**Comment by kratsg** [comment]
@johnda102 you should probably mention this issue in the pull request comment then: #604

**Comment by kratsg** [comment]
As #604 is merged in, this issue is closed as we now compile in 2.4.9.
