### ISSUE TITLE
xAH does not compile on > 21.2.114

### ISSUE THREAD

**Issue by jbossios** [UCATLAS/xAODAnaHelpers#1438]
I'm trying to make xAH work in newer releases (I know the recommended one is 21.2.113). I tried with 21.2.116 and 21.2.117 but in both, i get the following:

/afs/cern.ch/user/j/jbossios/work/public/SM/WZGroup/W+jets_13TeV/MakeTTrees_Wjets_Latest_170420/source/xAODAnaHelpers/Root/JetCalibrator.cxx: In member function 'virtual EL::StatusCode JetCalibrator::execute()':
/afs/cern.ch/user/j/jbossios/work/public/SM/WZGroup/W+jets_13TeV/MakeTTrees_Wjets_Latest_170420/source/xAODAnaHelpers/Root/JetCalibrator.cxx:457:29: error: 'class SmoothedWZTagger' has no member named 'decorateTruthLabel'; did you mean 'm_acc_truthLabel'?
  m_SmoothedWZTagger_handle->decorateTruthLabel(*jet_itr);
                             ^~~~~~~~~~~~~~~~~~
                             m_acc_truthLabel

I wanted to check that package and see what have changed but I was not able to find it. Does someone knows about a change in this tool or at least where I can find it?

**Comment by jbossios** [comment]
@mswiatlo 

I see you have a PR about truth labelling for large-R jets but you are not modifying the line which is causing me issues:
https://github.com/UCATLAS/xAODAnaHelpers/pull/1415/

**Comment by mswiatlo** [comment]
I think this all changed in https://gitlab.cern.ch/atlas/athena/-/commit/5df0a6e3c807501a175d7b8913b52c5c321648ab

But I haven't fully figured out how to update to this. In principle I think my MR will be unnecessary after this change in the base software, which drastically simplifies the large-R labeling procedure.

**Comment by jbossios** [comment]
Thanks @mswiatlo, I see that some derivations were updated now to have the needed decoration. What do we want to do here? Do we want to remove this and people just use what it should be in the derivation or do we want to implement the usage of the JetTruthLabelTool tool?

**Comment by kkrizka** [comment]
My impression is that the JetEtMiss recommendation is to transition to the usage of the tool. At least their twiki page does not mention anything about derivations:

https://twiki.cern.ch/twiki/bin/view/AtlasProtected/JetUncertaintiesRel21Summer2019LargeR#AnalysisBase_21_2_114_and_newer

**Comment by jbossios** [comment]
I see. If you have implemented the fix already please create a PR, if not, I can do it.

**Comment by matthewfeickert** [comment]
> I tried with 21.2.116 and 21.2.117 but in both,

@jbossios This actually comes in at release `21.2.114`. For posterity would you mind updating the PR title?

> I have already updated my fork of xAH. I can push the change here too. 

@kkrizka As this wasn't done on [your public fork of xAH on GitHub](https://github.com/kkrizka/xAODAnaHelpers) can you point us to where these changes live, or (if you have the time) would you mind opening up a PR?

**Comment by jrveatch** [comment]
This was just brought to my attention.  I'm putting together the fix now and will push it shortly.

**Comment by jrveatch** [comment]
This has been fixed in https://github.com/UCATLAS/xAODAnaHelpers/pull/1442.  I have done some local validation, but given my limited knowledge of xAH, I would not be surprised if it isn't extremely thorough.  If someone else could please validate it with their setup, it would be greatly appreciated.

**Comment by matthewfeickert** [comment]
>  If someone else could please validate it with their setup, it would be greatly appreciated.

Jason's PR passes CI from [AB release `21.2.114` through `21.2.121`](https://github.com/matthewfeickert/xAODAnaHelpers/runs/678353292?check_suite_focus=true) (run on my fork).

The CI range can get expanded in the PR as well to test above, but this also brings in the idea of what range to test in general.

**Comment by kratsg** [comment]
I'd just test the full range from 114-121
